### ISSUE TITLE
buffer length

### ISSUE THREAD

**Issue by robitmoh** [kroimon/Arduino-SerialCommand#8]
I cannot pass long parameter like "set_MLT_sensor 5E72631403A4FFFF"
because a buffer size is short
I think to change
from line 151 in SerialCommend.cpp
    if (bufPos > SERIALCOMMANDBUFFER-1) {
                    bufPos=0; // wrap buffer around if full  
                    Serial.println("Short SERIALCOMMANDBUFFER");
                }

**Comment by cgerome** [comment]
Hi all, I've been using this program and would like to know how and if possible to extend the SERIALCOMMANDBUFFER as this is limiting me to make my program evolve. the mains problem is that I'm giving something like 'P 130 20 22 39 1 3' and it is not doing anything but if I do 'P 130 2 3 1 1 3' it is working which is why i think it is an issue of the buffer. I was thinking to use two Scmd.addCommand to allow myself to pass all the information i want but not very clean solution. Thanks in advance for the support.

**Comment by ghost** [comment]
Hello, just edit lines (37, 39) in [SerialCommand.h](https://github.com/kroimon/Arduino-SerialCommand/blob/master/SerialCommand.h#L37-L39)
